### ISSUE TITLE
Parser.nextTokenType not cleared when rolling back from LexicalState

### ISSUE THREAD

**Issue by hylkevds** [javacc21/javacc21#180]
### Short summary:
When rolling back from a Lexical state, the variable `nextTokenType` in the `Parser` is not set to null, leading to checks using this variable giving wrong results.

### Minimal Demonstrator

```
PARSER_PACKAGE=ex1;
PARSER_CLASS=Calc;

SKIP : " " | "\t" | "\n" | "\r" ;

<DEFAULT> TOKEN : 
   <B : "b">
;

<STATE_A> TOKEN : 
   <A : "a">
;

FindA : STATE_A :
  <A> (<A>)*
;

Root : DEFAULT : FindA (<B>)* <EOF> ;


INJECT PARSER_CLASS : 
    import java.util.Scanner;
{
    static public void main(String[] args) throws ParseException {
       Scanner scanner = new Scanner("ab");
       String input = scanner.nextLine();
       PARSER_CLASS parser = new PARSER_CLASS(input);
       parser.Root();
       Node root = parser.rootNode();
       System.out.println("Dumping the AST...");
       root.dump();
    }
}
```

Running this gives:
```
Exception in thread "main" ex1.ParseException: 
Encountered an error at (or somewhere around) input:1:2
Was expecting one of the following:
EOF
Found string "b" of type B
	at ex1.Calc.handleUnexpectedTokenType(Calc.java:404)
	at ex1.Calc.consumeToken(Calc.java:393)
	at ex1.Calc.Root(Calc.java:271)
	at ex1.Calc.main(Calc.java:26)
```

### Analysis
There are two lexical states: 
- `DEFAULT` only matches b
- `STATE_A` only matches a.

The Parser main tries to match the string `ab`
1. Root starts in state `DEFAULT` and passes to `FindA`.
2. `FindA` switches to lexical state `STATE_A`
3. `<A>` find the first `a` in the input.
4. `(<A>)*` fails, since the input only contains a b, and sets the `nextTokenType` to the invalid token type.
5. Returning from `FindA` resets the Lexer, but does not clear the `nextTokenType`. (Line 224 - 231)
6. The `(<B>)*` uses a check against `nextTokenType()` (Line 264), which in turn uses the cached `nextTokenType` since it is not null, but the invalid token type.

Setting `nextTokenType` to null when reverting the lexical state should fix this. This will cause `nextTokenType()` to actually request a new token from the lexer, using the corrext lexical state.
I don't know if this can also happen when forward-switching to a new lexical state.

It also shows the generated parser is easy to understand! Pinpointing the issue on a much larger and very messy work-in-progress didn't take that long.

**Comment by revusky** [comment]
Hmm, this is probably not so hard to solve. Let's see... Could you check this: if you rewrite the FindA production as:

     FindA : 
        LEXICAL_STATE STATE_A (<A> (<A>)*)
    ;

does this work?

You see, I wrote a C# grammar earlier this year and, for the first time, I really used this lexical state switching machinery, and I discovered that it was broken. I think it was working back when I wrote the code, but maybe code drift in the preceding year... but I had used this other way of doing things, you see, so maybe it's still broken if you annotate the production itself with the lexical state. You can see the code in question here: 

https://github.com/javacc21/javacc21/blob/master/examples/csharp/CSharp.javacc#L2154

which uses this lexical state switching machinery to handle interpolated strings (a feature that does not exist in Java)

And that is all working now, I'm pretty sure. But it seems there may be a bug in the other way of writing this, where you annotate the production itself.

**Comment by hylkevds** [comment]
That results in the same error. Comparing the generated code, the blocks are moved around a bit, but not fundamentally different.

In both cases, FindA ends because of the check
```
if (!(nextTokenType()== A)) break;
```
And that check caches the result in `nextTokenType`.
Since the Root production uses essentially the same test:
```
if (!(nextTokenType()== B)) break;
```
it re-uses the non-cleared result, that was produced by the previous Lexical State.

This problem does not occur if `FindA` ends on a non-optional match, like:
```
FindA : STATE_A :
 <A>
;
```
Since in that case there is no call to `nextTokenType()` in `FindA`, and thus no cached value.
Or, if the Root does not have an optional match after `FindA`, like:
```
Root : DEFAULT : FindA <B> <EOF> ;
```
Since in that case there is no call to `nextTokenType()` in `Root` and thus the cached value is not used.

**Comment by hylkevds** [comment]
Looking at the C# grammar you linked, they don't have the problem, since those productions end in a non-optional bit, and thus end with a call to `consumeToken()`, which has: `this.nextTokenType= null;`.

The problem also does not manifest when the cached token type is one that is shared by the two productions.

**Comment by revusky** [comment]
> Looking at the C# grammar you linked, they don't have the problem, since those productions end in a non-optional bit, and thus end with a call to `consumeToken()`, which has: `this.nextTokenType= null;`.

I see. So I guess the question of specifying the lexical state at the production-level or at the expansion level is probably a red herring.

> 
> The problem also may not manifest when the cached token type is one that is shared by the two productions, though the result may be incorrect in that case.

Quite possibly this bug is not due to code drift. It was always there. Though that hardly matters. The important thing is to fix it now.

Stay tuned.

**Comment by revusky** [comment]
Well, I think it's fixed now. Quite trivially. It's just a [one line insertion](https://github.com/javacc21/javacc21/commit/e54e404b2025259be9c66e8dd54521c9070adb40#diff-17fd93902b289a97aba4290e7a520b5127f259c271e3d77bafd9c67e1184c658R135)

A funny thing about this is that the line was there in the block below that for activating/deactivating individual tokens. See [here](https://github.com/javacc21/javacc21/blob/master/src/ftl/java/CommonUtils.java.ftl#L159) but it was missing in the previous block. It is now on [line 135 of that file](https://github.com/javacc21/javacc21/blob/master/src/ftl/java/CommonUtils.java.ftl#L135). 

If you still have problems with this, do report back. If not, I guess I'll be able to close the issue. 

Thanks for the help.
