### ISSUE TITLE
Unclear exception on unused anonymous token in unused lexical state

### ISSUE THREAD

**Issue by hylkevds** [javacc21/javacc21#182]
This issue is probably mostly user error, but when it happens it will leave the user quite puzzled about what is wrong with their parser definition. So I figured I'd report it any way in case someone else runs into it.

The minimal reproducer:
```
<DUMMY> TOKEN:
    <#UNUSED_B : "b" >
;

<DEFAULT> TOKEN : 
    <A : "a" >
;

Root : DEFAULT : <A> <EOF> ;
```
This generates an exception when generating the parser. It is caused by the unused `<#UNUSED_B : "b" >` inside an unused lexical state `<DUMMY>`. Moving the `<#UNUSED_B : "b" >` inside the `<DEFAULT>` state makes the exception go away. Changing it to `<UNUSED_B : "b" >` also makes the exception go away.

It would be great if the exception could be made a little clearer.

The exception:
```
SEVERE: get(nextStateType) failed on instance of com.javacc.core.NfaState

get(nextStateType) failed on instance of com.javacc.core.NfaState
----------
==> variable declaration [on line 208, column 5 in NfaData.java.ftl]
 in user-directive GenerateSimpleNfaMethod [on line 127, column 8 in NfaData.java.ftl]
 in user-directive GenerateStateCode [on line 110, column 4 in NfaData.java.ftl]
----------

Java backtrace for programmers:
----------
freemarker.template.TemplateModelException: get(nextStateType) failed on instance of com.javacc.core.NfaState
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:184)
	at freemarker.core.ast.Dot._getAsTemplateModel(Dot.java:58)
	at freemarker.core.ast.Expression.getAsTemplateModel(Expression.java:72)
	at freemarker.core.ast.VarDirective.execute(VarDirective.java:48)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.MixedContent.execute(MixedContent.java:70)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.Environment.renderSecurely(Environment.java:240)
	at freemarker.core.MacroContext.runMacro(MacroContext.java:61)
	at freemarker.core.Environment.render(Environment.java:587)
	at freemarker.core.ast.UnifiedCall.execute(UnifiedCall.java:94)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.MixedContent.execute(MixedContent.java:70)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.ConditionalBlock.execute(ConditionalBlock.java:66)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.IfBlock.execute(IfBlock.java:60)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.MixedContent.execute(MixedContent.java:70)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.LoopContext.runLoop(LoopContext.java:71)
	at freemarker.core.Environment.process(Environment.java:443)
	at freemarker.core.ast.IteratorBlock.execute(IteratorBlock.java:69)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.MixedContent.execute(MixedContent.java:70)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.Environment.renderSecurely(Environment.java:240)
	at freemarker.core.MacroContext.runMacro(MacroContext.java:61)
	at freemarker.core.Environment.render(Environment.java:587)
	at freemarker.core.ast.UnifiedCall.execute(UnifiedCall.java:94)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.MixedContent.execute(MixedContent.java:70)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.LoopContext.runLoop(LoopContext.java:71)
	at freemarker.core.Environment.process(Environment.java:443)
	at freemarker.core.ast.IteratorBlock.execute(IteratorBlock.java:69)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.ast.MixedContent.execute(MixedContent.java:70)
	at freemarker.core.Environment.render(Environment.java:256)
	at freemarker.core.Environment.renderSecurely(Environment.java:240)
	at freemarker.core.Environment.process(Environment.java:206)
	at freemarker.template.Template.process(Template.java:276)
	at com.javacc.output.java.FilesGenerator.generate(FilesGenerator.java:229)
	at com.javacc.output.java.FilesGenerator.generate(FilesGenerator.java:163)
	at com.javacc.output.java.FilesGenerator.generateNfaData(FilesGenerator.java:315)
	at com.javacc.output.java.FilesGenerator.generateAll(FilesGenerator.java:105)
	at com.javacc.Grammar.generateFiles(Grammar.java:348)
	at com.javacc.Main.mainProgram(Main.java:351)
	at com.javacc.Main.main(Main.java:327)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:773)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:236)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:151)
	... 48 more
Caused by: java.lang.NullPointerException
	at com.javacc.core.NfaState.getNextStateType(NfaState.java:118)
	... 55 more
```

**Comment by revusky** [comment]
Yeah, I see the problem. The reason for the error is that the DUMMY lexical state you define actually does not define any token type at all. And given the internal logic of the system, when it goes and tries to generate the state machine for that lexical state, it hits an exception. And that makes sense basically, so really the whole issue is just that it should provide a human readable error message in this spot, rather than spitting out the stack trace, which is incomprehensible.

As you probably understand already, the "private" type #UNUSED_B is actually just a macro really, a regular expression that can be used internally inside of another regexp. So, for example, if you remove the '#' character from in front, it will build okay because the DUMMY lexical state now does have a token type.

So, thanks again. I'll surely fix this at some point soon.

**Comment by revusky** [comment]
Okay, I think we should be okay on this now. 

Hey, I was wondering... out of curiosity, did you ever read [this blog post](https://javacc.com/2020/10/28/a-bugs-life/)?

**Comment by hylkevds** [comment]
Yep, that's a nice and understandable error it now gives. Thanks for the fast response.

I had not read that post yet. A certain [Monty Python sketch](https://en.wikipedia.org/wiki/Dead_Parrot_sketch) comes to mind... I'm glad I wasn't the one to report it ;)
