### ISSUE TITLE
An odd exception

### ISSUE THREAD

**Issue by hylkevds** [javacc21/javacc21#184]
This parser definition gives an odd exception. The fact that is gives an error is not strange, since it's obviously an incorrect parser, but it's not the error I was expecting, and hence it took a while to find the actual cause.

The (roughly) smallest definition in question that gives the error:
```
TOKEN:
 <LONG: ( <SIGN> )? (["0"-"9"] | ["1"-"9"](["0"-"9"])+) >
;

Start :
  Options <EOF>
;
```

I was expecting either "Options not found" or "SIGN not found".
Adding either an Options production, _or_ a SIGN Token does not fix the exception. 
Only adding _both_ an Options production _and_ a SIGN token makes the exception go away.

The Exception:
```
JavaCC 21 Parser Generator (javacc-full.jar built by revusky on 2022-05-21)
Go to https://javacc.com for more information.
(type "java -jar javacc.jar" with no arguments for help)


Exception in thread "main" java.lang.NullPointerException
	at com.javacc.parser.Node$Visitor.getVisitMethod(Node.java:704)
	at com.javacc.parser.Node$Visitor.visit(Node.java:746)
	at com.javacc.core.NfaBuilder.visit(NfaBuilder.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javacc.parser.Node$Visitor.visit(Node.java:751)
	at com.javacc.core.NfaBuilder.visit(NfaBuilder.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javacc.parser.Node$Visitor.visit(Node.java:751)
	at com.javacc.core.NfaBuilder.visit(NfaBuilder.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javacc.parser.Node$Visitor.visit(Node.java:751)
	at com.javacc.core.NfaBuilder.visit(NfaBuilder.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javacc.parser.Node$Visitor.visit(Node.java:751)
	at com.javacc.core.NfaBuilder.buildStates(NfaBuilder.java:63)
	at com.javacc.core.LexicalStateData.processTokenProduction(LexicalStateData.java:189)
	at com.javacc.core.LexicalStateData.process(LexicalStateData.java:126)
	at com.javacc.core.LexerData.buildData(LexerData.java:221)
	at com.javacc.Grammar.generateLexer(Grammar.java:327)
	at com.javacc.Main.mainProgram(Main.java:346)
	at com.javacc.Main.main(Main.java:327)
```

**Comment by revusky** [comment]
This issue was introduced in the last fix actually. The problem is just that it was continuing after hitting the error that the regexp was undefined and then hitting the NPE. It should abort processing at that point. There is one little annoyane that it seems to report the error twice but I'm not 100% sure that that was not present before. But that is not a big problem. I'll look into that later.
