### ISSUE TITLE
I just added a CSLex.java analogous to JLex.java, but it fails on many files

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#202]
I might be doing something dumb, but I can't see what that might be :disappointed: 
```text
$ java CSLex testfiles -q 2>&1 | grep -v "tokenized successfully."
Error processing file: testfiles/MethodInfoTest.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/MethodInfoTest.cs:907:54
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/RouteHandlerEndpointRouteBuilderExtensionsTest.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/RouteHandlerEndpointRouteBuilderExtensionsTest.cs:524:58
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/AdaptiveCapacityDictionary.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/AdaptiveCapacityDictionary.cs:233:71
Found string "\'" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/IterateOverTuple.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/IterateOverTuple.cs:105:58
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/EndpointMetadataApiDescriptionProviderTest.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/EndpointMetadataApiDescriptionProviderTest.cs:1085:82
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/ValidationWithRecordIntegrationTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/ValidationWithRecordIntegrationTests.cs:1151:19
Found string "\'" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/CSCProgram.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/CSCProgram.cs:33:95
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/MemberSemanticModel.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/MemberSemanticModel.cs:2297:137
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/Startup.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/Startup.cs:53:30
Found string "\'" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/Lexer_RawStringLiteral.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/Lexer_RawStringLiteral.cs:403:25
Found string "\\" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/SyntacticQuickInfoSourceTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/SyntacticQuickInfoSourceTests.cs:291:29
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/RebuildCommandLineTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/RebuildCommandLineTests.cs:233:110
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/DfaMatcherBuilder.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/DfaMatcherBuilder.cs:442:126
Found string "\'" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/WebApplicationTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/WebApplicationTests.cs:242:58
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/sample.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/sample.cs:84:91
Found string "°" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/TypeWithState.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/TypeWithState.cs:77:104
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/Driver.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/Driver.cs:320:83
Found string "`" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/WebAssemblyHttpHandler.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/WebAssemblyHttpHandler.cs:177:142
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/WebConnection.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/WebConnection.cs:224:92
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/DefaultHubDispatcher.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/DefaultHubDispatcher.cs:184:93
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/TypeTest.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/TypeTest.cs:5020:62
Found string "`" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/WebOperation.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/WebOperation.cs:136:53
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/ClientWebSocket.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/ClientWebSocket.cs:282:92
Found string "\'" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/RemoveUnnecessaryPragmaSuppressionsTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/RemoveUnnecessaryPragmaSuppressionsTests.cs:211:3
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/TestClient.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/TestClient.cs:138:108
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/TypedArray.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/TypedArray.cs:114:113
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/RebuildSourceReferenceResolver.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/RebuildSourceReferenceResolver.cs:58:33
Found string "\\" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/ResponseTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/ResponseTests.cs:54:111
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/SuppressionTests.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/SuppressionTests.cs:74:3
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Error processing file: testfiles/ValueSetFactory.DecimalTC.cs
org.parsers.csharp.ParseException:
Encountered an error at (or somewhere around) testfiles/ValueSetFactory.DecimalTC.cs:106:106
Found string "\"" of type INVALID
  at CSLex.tokenizeFile(CSLex.java:67)
  at CSLex.main(CSLex.java:41)
Lexing failed on: testfiles/MethodInfoTest.cs
Lexing failed on: testfiles/RouteHandlerEndpointRouteBuilderExtensionsTest.cs
Lexing failed on: testfiles/AdaptiveCapacityDictionary.cs
Lexing failed on: testfiles/IterateOverTuple.cs
Lexing failed on: testfiles/EndpointMetadataApiDescriptionProviderTest.cs
Lexing failed on: testfiles/ValidationWithRecordIntegrationTests.cs
Lexing failed on: testfiles/CSCProgram.cs
Lexing failed on: testfiles/MemberSemanticModel.cs
Lexing failed on: testfiles/Startup.cs
Lexing failed on: testfiles/Lexer_RawStringLiteral.cs
Lexing failed on: testfiles/SyntacticQuickInfoSourceTests.cs
Lexing failed on: testfiles/RebuildCommandLineTests.cs
Lexing failed on: testfiles/DfaMatcherBuilder.cs
Lexing failed on: testfiles/WebApplicationTests.cs
Lexing failed on: testfiles/sample.cs
Lexing failed on: testfiles/TypeWithState.cs
Lexing failed on: testfiles/Driver.cs
Lexing failed on: testfiles/WebAssemblyHttpHandler.cs
Lexing failed on: testfiles/WebConnection.cs
Lexing failed on: testfiles/DefaultHubDispatcher.cs
Lexing failed on: testfiles/TypeTest.cs
Lexing failed on: testfiles/WebOperation.cs
Lexing failed on: testfiles/ClientWebSocket.cs
Lexing failed on: testfiles/RemoveUnnecessaryPragmaSuppressionsTests.cs
Lexing failed on: testfiles/TestClient.cs
Lexing failed on: testfiles/TypedArray.cs
Lexing failed on: testfiles/RebuildSourceReferenceResolver.cs
Lexing failed on: testfiles/ResponseTests.cs
Lexing failed on: testfiles/SuppressionTests.cs
Lexing failed on: testfiles/ValueSetFactory.DecimalTC.cs

Tokenized 107 files, containing 405500 tokens.
Failed on 30 files.
```

**Comment by revusky** [comment]
Well, just offhand (I haven't looked at it too closely) I would think that you are likely hitting problems related to lexical state swiches (and/or token activation/deactivation).  Or, in particular, if you look at the last 5 productions in CSharp.javacc, i.e. https://github.com/javacc21/javacc21/blob/master/examples/csharp/CSharp.javacc#L2155

and you see the lexical state switches. Well, I guess the long and short of it is that it may be just about impossible to write a context-free pure lexer for CSharp.

**Comment by vsajip** [comment]
Ah, OK. At least some of the errors are in special strings - so lexical state changes are the likely cause.
