### ISSUE TITLE
Double-clickable filename locations in stack traces and such

### ISSUE THREAD

**Issue by revusky** [javacc21/javacc21#43]
In the last day or two I became obsessed with having locations be double-clickable. (Or really, it's more typically ctrl-clickable, but that does not matter much.) Actually, that is the logical continuation of some work I did earlier. For example, consider the following stacktrace:

<CODE>
Exception in thread "main" com.javacc.parser.ParseException: 
Encountered an error at (or somewhere around) Java.javacc:573:11
Was expecting one of the following:
RPAREN
Found string "\\" of type BACKSLASH
        at com.javacc.parser.JavaCCParser.handleUnexpectedTokenType(JavaCCParser.java:31569)
        at com.javacc.parser.JavaCCParser.consumeToken(JavaCCParser.java:31557)
        at com.javacc.parser.JavaCCParser.Arguments(JavaCCParser.java:5914)
        at JavaCCParser.NonTerminal(src/main/grammars/JavaCC.javacc:1966)
        at com.javacc.parser.JavaCCParser.NonTerminal(JavaCCParser.java:12470)
        at JavaCCParser.ExpansionUnit(src/main/grammars/JavaCC.javacc:1937)
        at com.javacc.parser.JavaCCParser.ExpansionUnit(JavaCCParser.java:12314)
        at JavaCCParser.ExpansionSequence(src/main/grammars/JavaCC.javacc:1382)
        at com.javacc.parser.JavaCCParser.ExpansionSequence(JavaCCParser.java:11323)
        at JavaCCParser.ExpansionChoice(src/main/grammars/JavaCC.javacc:1290)
        at com.javacc.parser.JavaCCParser.ExpansionChoice(JavaCCParser.java:11238)
        at JavaCCParser.BNFProduction(src/main/grammars/JavaCC.javacc:898)
        at com.javacc.parser.JavaCCParser.BNFProduction(JavaCCParser.java:10756)
        at JavaCCParser.Root(src/main/grammars/JavaCC.javacc:655)
        at com.javacc.parser.JavaCCParser.Root(JavaCCParser.java:9774)
</CODE>

Notice how the stack trace provides locations that correspond to the *generated* JavaCCParser.java file AND also the original JavaCC grammar file! This is the result of some work I did some months ago [here](https://github.com/javacc21/javacc21/blob/master/src/main/resources/templates/java/ParseException.java.ftl#L148). For example, in the line:

     at JavaCCParser.NonTerminal(src/main/grammars/JavaCC.javacc:1966)

I can click on the location in parentheses in either a VSCode terminal or in iTerm2 on the mac, and it goes straight to the location. In iTerm2, it does the exact same thing because I configured it to open these locations using VSCode. I could also configure it to open it in IntelliJ or Eclipse or in some other editor. The reason I introduced the [bug here](https://github.com/javacc21/javacc21/issues/42) is because I was playing around with providing the full filepath, but forgot about this really annoying stuff on Windows with the path separators, so something like:

     C:\some\dir\MyGrammar.javacc

also has to be replaced with:

    C:\\some\\dir\\MyGrammar.javacc

if you're going to embed it in a literal string. Stuff like this. Somehow I had "forgotten" about all this stuff! Total pain in the ass!

Well, I'm opening this issue because I have decided that I am concerned with locations in stack traces and such being double-clickable, at least in as broad a range of environments as possible. (It would be great to eventually have full debugger integration, but already this is quite useful!)

Another thing is that I changed the format of the various location information that I insert into a file. So I now have things like:

            // Code for ZeroOrOne specified at:
            // Java.javacc:355:3
            if (scan$Java_javacc$355$5()) {
                // Code for NonTerminal specified at:
                // Java.javacc:355:5
                pushOntoCallStack("CompilationUnit", "Java.javacc", 355, 5);

I would very very much like Java.javacc:355:3 to be double-clickable within VSCode (or anywhere else, like Eclipse or IntelliJ!)

It's not so onerous to open the file manually and go to the line number, I suppose, but it's just much nicer to be able to Ctrl-click on the location and go straight there. But, anyway, I myself am not going to work on this much more for now. I figured this whole thing of the clickability of the file locations in various work environments like VSCode etcetera, is extremely useful and not so difficult. It good be a good thing to bite off and take ownership of. (Especially if you happen to be a Frenchman whose initials are AZ.)

Anyway, I open this issue so it's there and we can maybe eventually even just close it!

**Comment by revusky** [comment]
I don't know why this is still open. In any case, all activity should be over on CongoCC
