### ISSUE TITLE
NPE caused by typo in grammar file

### ISSUE THREAD

**Issue by vsajip** [javacc21/javacc21#81]
If instead of typing
```
Foo : Bar #BarClass ;
```
you accidentally leave out `BarClass` -
```
Foo : Bar # ;
```
you get the NPE:
```
Exception in thread "main" java.lang.NullPointerException
	at com.javacc.Grammar.addNodeType(Grammar.java:762)
	at com.javacc.core.Expansion.setTreeNodeBehavior(Expansion.java:128)
	at com.javacc.parser.JavaCCParser.ExpansionUnit(JavaCCParser.java:13975)
	at com.javacc.parser.JavaCCParser.ExpansionSequence(JavaCCParser.java:12892)
	at com.javacc.parser.JavaCCParser.ExpansionChoice(JavaCCParser.java:12655)
	at com.javacc.parser.JavaCCParser.BNFProduction(JavaCCParser.java:12115)
	at com.javacc.parser.JavaCCParser.Root(JavaCCParser.java:10928)
	at com.javacc.Grammar.parse(Grammar.java:205)
	at com.javacc.Main.mainProgram(Main.java:321)
	at com.javacc.Main.main(Main.java:305)
```

**Comment by revusky** [comment]
Yes, thanks. I'm aware of that actually. Well, since yesterday, since I ran into this yesterday. The problem seems to be that the enhancement that I added here : https://javacc.com/2021/01/14/tree-building-dmitry-dmitryevich-dmitryev/

The shorthand where you can annotate a production like so:

       Foobar# : ....;

instead of `Foobar#Foobar`

This only works on a production, but not on an expansion within a production, so writing:

      Foobar #

inside a production leads to the NPE. Well, the solution I'm leaning towards is just allowing the shorthand when annotating a production but not an expansion, I guess. You'll typically write something like:

     (Foo Bar) #Foobar

And if you were to try to leave out the Foobar name, it doesn't have an automatic default name. Whereas, if you are annotating a production, you have the production (i.e. the method) name to use as a default.
